threads: 5                                           # THREADS Amount
solver: "CAPSOLVER"                                           # CAPSOLVER , CAPBYPASS
capKey: "CAP-143855FEB2B78DCFA40C087EEA6B71D1"                                           # CAPTCHA KEY  
